/********************************************************************************
** Form generated from reading UI file 'eeprom.ui'
**
** Created by: Qt User Interface Compiler version 5.14.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EEPROM_H
#define UI_EEPROM_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Eeprom
{
public:
    QWidget *layoutWidget;
    QHBoxLayout *hboxLayout;
    QPushButton *SaveEepromBtn;
    QPushButton *CancelEepromBtn;
    QTabWidget *tabWidget;
    QWidget *DetectorTab;
    QComboBox *SensorComboBox;
    QLineEdit *NrPixelsEdt;
    QGroupBox *groupBox;
    QLineEdit *WavCalInterceptEdt;
    QLineEdit *WavCalX1Edt;
    QLineEdit *WavCalX2Edt;
    QLineEdit *WavCalX3Edt;
    QLineEdit *WavCalX4Edt;
    QGroupBox *groupBox_2;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QGroupBox *groupBox_3;
    QLineEdit *NonLinInterceptEdt;
    QLineEdit *NonLinX1Edt;
    QLineEdit *NonLinX2Edt;
    QLineEdit *NonLinX3Edt;
    QLineEdit *NonLinX4Edt;
    QLineEdit *NonLinX5Edt;
    QLineEdit *NonLinX6Edt;
    QLineEdit *NonLinX7Edt;
    QLineEdit *LoCountsEdt;
    QLineEdit *HiCountsEdt;
    QCheckBox *NonLinEnableChk;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QGroupBox *groupBox_4;
    QTextEdit *DefectEdt;
    QLineEdit *Gain1Edt;
    QLineEdit *Gain2Edt;
    QLineEdit *Offset1Edt;
    QLineEdit *Offset2Edt;
    QLineEdit *ExtOffsetEdt;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QWidget *StandaloneTab;
    QCheckBox *EnableStandAloneChk;
    QGroupBox *groupBox_5;
    QGroupBox *groupBox_8;
    QLineEdit *FlashesPerScanEdt;
    QLineEdit *LaserDelayEdt;
    QLineEdit *LaserWidtEdt;
    QLineEdit *LaserWavEdt;
    QLineEdit *StoreToRamEdt;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QGroupBox *groupBox_9;
    QLineEdit *DarkPercentageEdt;
    QCheckBox *DarkCorrEnableChk;
    QLabel *label_54;
    QLineEdit *StartPixelEdt;
    QLineEdit *StopPixelEdt;
    QLineEdit *IntTimeEdt;
    QLineEdit *IntDelayEdt;
    QLineEdit *NrAveragesEdt;
    QLineEdit *SatDetectEdt;
    QLabel *label_6;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QGroupBox *groupBox_11;
    QLineEdit *SmoothModelEdt;
    QLineEdit *SmoothPixelsEdt;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QGroupBox *groupBox_7;
    QGroupBox *groupBox_18;
    QRadioButton *HardwareTriggerRBtn;
    QRadioButton *SoftwareTriggerRBtn;
    QGroupBox *groupBox_19;
    QRadioButton *ExternalTriggerRbtn;
    QRadioButton *SynchTriggerRBtn;
    QGroupBox *groupBox_21;
    QRadioButton *EdgeTriggerRBtn;
    QRadioButton *LevelTriggerRBtn;
    QGroupBox *groupBox_6;
    QGroupBox *groupBox_10;
    QCheckBox *GetTimeStampChk;
    QLineEdit *DateNrEdt;
    QLineEdit *TimeNrEdt;
    QLineEdit *DayEdt;
    QLineEdit *MonthEdt;
    QLineEdit *YearEdt;
    QLineEdit *SecEdt;
    QLineEdit *MinEdt;
    QLineEdit *HourEdt;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QCheckBox *SDCardEnableChk;
    QLineEdit *SpectrumTypeEdt;
    QLineEdit *FileRootNameEdt;
    QLabel *label_44;
    QLabel *label_45;
    QLineEdit *NrMeasEdt;
    QLabel *label_43;
    QWidget *IrradianceTab;
    QGroupBox *groupBox_12;
    QGroupBox *groupBox_13;
    QLineEdit *IrradianceSmoothModelEdt;
    QLineEdit *IrradianceSmoothPixelsEdt;
    QLabel *label_55;
    QLabel *label_56;
    QTextEdit *IrradianceConvEdt;
    QLineEdit *IrradianceIntTimeEdt;
    QLabel *label_57;
    QLineEdit *IrradCalibrationTypeEdt;
    QLineEdit *IrradFiberDiameterEdt;
    QLabel *label_58;
    QLabel *label_59;
    QWidget *ReflectanceTab;
    QGroupBox *groupBox_14;
    QGroupBox *groupBox_15;
    QLineEdit *ReflectanceSmoothModelEdt;
    QLineEdit *ReflectanceSmoothPixelsEdt;
    QLabel *label_60;
    QLabel *label_61;
    QTextEdit *ReflectanceCorrEdt;
    QLineEdit *ReflectanceIntTimeEdt;
    QLabel *label_62;
    QWidget *SpectrumTab;
    QGroupBox *groupBox_16;
    QTextEdit *SpectrumCorrEdt;
    QWidget *TemperatureTab;
    QGroupBox *groupBox_17;
    QLineEdit *NTC1X0Edt;
    QLineEdit *NTC1X1Edt;
    QLineEdit *NTC1X3Edt;
    QLineEdit *NTC1X4Edt;
    QLineEdit *NTC1X2Edt;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QGroupBox *groupBox_20;
    QLineEdit *NTC2X0Edt;
    QLineEdit *NTC2X1Edt;
    QLineEdit *NTC2X3Edt;
    QLineEdit *NTC2X4Edt;
    QLineEdit *NTC2X2Edt;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QGroupBox *groupBox_23;
    QLineEdit *ThermistorX0Edt;
    QLineEdit *ThermistorX1Edt;
    QLineEdit *ThermistorX3Edt;
    QLineEdit *ThermistorX4Edt;
    QLineEdit *ThermistorX2Edt;
    QLabel *label_93;
    QLabel *label_94;
    QLabel *label_95;
    QLabel *label_96;
    QLabel *label_97;
    QWidget *TecTab;
    QGroupBox *groupBox_24;
    QLineEdit *TECX0Edt;
    QLineEdit *TECX1Edt;
    QLabel *label_99;
    QLabel *label_100;
    QCheckBox *TECEnableChk;
    QLineEdit *SetPointEdt;
    QLabel *label_98;
    QLineEdit *StrucLengthEdt;
    QLineEdit *StrucVersionEdt;
    QLineEdit *FriendlyEdt;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;

    void setupUi(QDialog *Eeprom)
    {
        if (Eeprom->objectName().isEmpty())
            Eeprom->setObjectName(QString::fromUtf8("Eeprom"));
        Eeprom->resize(832, 695);
        QFont font;
        font.setFamily(QString::fromUtf8("Sans Serif"));
        font.setPointSize(8);
        Eeprom->setFont(font);
        layoutWidget = new QWidget(Eeprom);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(430, 650, 341, 31));
        hboxLayout = new QHBoxLayout(layoutWidget);
#ifndef Q_OS_MAC
        hboxLayout->setSpacing(6);
#endif
        hboxLayout->setContentsMargins(0, 0, 0, 0);
        hboxLayout->setObjectName(QString::fromUtf8("hboxLayout"));
        hboxLayout->setContentsMargins(0, 0, 0, 0);
        SaveEepromBtn = new QPushButton(layoutWidget);
        SaveEepromBtn->setObjectName(QString::fromUtf8("SaveEepromBtn"));

        hboxLayout->addWidget(SaveEepromBtn);

        CancelEepromBtn = new QPushButton(layoutWidget);
        CancelEepromBtn->setObjectName(QString::fromUtf8("CancelEepromBtn"));

        hboxLayout->addWidget(CancelEepromBtn);

        CancelEepromBtn->raise();
        SaveEepromBtn->raise();
        tabWidget = new QTabWidget(Eeprom);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(30, 110, 751, 521));
        DetectorTab = new QWidget();
        DetectorTab->setObjectName(QString::fromUtf8("DetectorTab"));
        SensorComboBox = new QComboBox(DetectorTab);
        SensorComboBox->setObjectName(QString::fromUtf8("SensorComboBox"));
        SensorComboBox->setGeometry(QRect(123, 40, 141, 22));
        NrPixelsEdt = new QLineEdit(DetectorTab);
        NrPixelsEdt->setObjectName(QString::fromUtf8("NrPixelsEdt"));
        NrPixelsEdt->setGeometry(QRect(122, 70, 141, 20));
        groupBox = new QGroupBox(DetectorTab);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(40, 110, 231, 171));
        WavCalInterceptEdt = new QLineEdit(groupBox);
        WavCalInterceptEdt->setObjectName(QString::fromUtf8("WavCalInterceptEdt"));
        WavCalInterceptEdt->setGeometry(QRect(90, 20, 113, 20));
        WavCalX1Edt = new QLineEdit(groupBox);
        WavCalX1Edt->setObjectName(QString::fromUtf8("WavCalX1Edt"));
        WavCalX1Edt->setGeometry(QRect(90, 50, 113, 20));
        WavCalX2Edt = new QLineEdit(groupBox);
        WavCalX2Edt->setObjectName(QString::fromUtf8("WavCalX2Edt"));
        WavCalX2Edt->setGeometry(QRect(90, 80, 113, 20));
        WavCalX3Edt = new QLineEdit(groupBox);
        WavCalX3Edt->setObjectName(QString::fromUtf8("WavCalX3Edt"));
        WavCalX3Edt->setGeometry(QRect(90, 110, 113, 20));
        WavCalX4Edt = new QLineEdit(groupBox);
        WavCalX4Edt->setObjectName(QString::fromUtf8("WavCalX4Edt"));
        WavCalX4Edt->setGeometry(QRect(90, 140, 113, 20));
        groupBox_2 = new QGroupBox(groupBox);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(30, 200, 231, 161));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(10, 20, 71, 16));
        label_8 = new QLabel(groupBox);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 50, 46, 14));
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 80, 46, 14));
        label_10 = new QLabel(groupBox);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 110, 46, 14));
        label_11 = new QLabel(groupBox);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 140, 46, 14));
        groupBox_3 = new QGroupBox(DetectorTab);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(350, 40, 241, 281));
        NonLinInterceptEdt = new QLineEdit(groupBox_3);
        NonLinInterceptEdt->setObjectName(QString::fromUtf8("NonLinInterceptEdt"));
        NonLinInterceptEdt->setGeometry(QRect(80, 20, 113, 20));
        NonLinX1Edt = new QLineEdit(groupBox_3);
        NonLinX1Edt->setObjectName(QString::fromUtf8("NonLinX1Edt"));
        NonLinX1Edt->setGeometry(QRect(80, 40, 113, 20));
        NonLinX2Edt = new QLineEdit(groupBox_3);
        NonLinX2Edt->setObjectName(QString::fromUtf8("NonLinX2Edt"));
        NonLinX2Edt->setGeometry(QRect(80, 60, 113, 20));
        NonLinX3Edt = new QLineEdit(groupBox_3);
        NonLinX3Edt->setObjectName(QString::fromUtf8("NonLinX3Edt"));
        NonLinX3Edt->setGeometry(QRect(80, 80, 113, 20));
        NonLinX4Edt = new QLineEdit(groupBox_3);
        NonLinX4Edt->setObjectName(QString::fromUtf8("NonLinX4Edt"));
        NonLinX4Edt->setGeometry(QRect(80, 100, 113, 20));
        NonLinX5Edt = new QLineEdit(groupBox_3);
        NonLinX5Edt->setObjectName(QString::fromUtf8("NonLinX5Edt"));
        NonLinX5Edt->setGeometry(QRect(80, 120, 113, 20));
        NonLinX6Edt = new QLineEdit(groupBox_3);
        NonLinX6Edt->setObjectName(QString::fromUtf8("NonLinX6Edt"));
        NonLinX6Edt->setGeometry(QRect(80, 140, 113, 20));
        NonLinX7Edt = new QLineEdit(groupBox_3);
        NonLinX7Edt->setObjectName(QString::fromUtf8("NonLinX7Edt"));
        NonLinX7Edt->setGeometry(QRect(80, 160, 113, 20));
        LoCountsEdt = new QLineEdit(groupBox_3);
        LoCountsEdt->setObjectName(QString::fromUtf8("LoCountsEdt"));
        LoCountsEdt->setGeometry(QRect(80, 200, 113, 20));
        HiCountsEdt = new QLineEdit(groupBox_3);
        HiCountsEdt->setObjectName(QString::fromUtf8("HiCountsEdt"));
        HiCountsEdt->setGeometry(QRect(80, 220, 113, 20));
        NonLinEnableChk = new QCheckBox(groupBox_3);
        NonLinEnableChk->setObjectName(QString::fromUtf8("NonLinEnableChk"));
        NonLinEnableChk->setGeometry(QRect(10, 250, 211, 19));
        label_12 = new QLabel(groupBox_3);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 20, 61, 16));
        label_13 = new QLabel(groupBox_3);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 40, 46, 14));
        label_14 = new QLabel(groupBox_3);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 60, 46, 14));
        label_15 = new QLabel(groupBox_3);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(10, 80, 46, 14));
        label_16 = new QLabel(groupBox_3);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 100, 46, 14));
        label_17 = new QLabel(groupBox_3);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(10, 120, 46, 14));
        label_18 = new QLabel(groupBox_3);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 140, 46, 14));
        label_19 = new QLabel(groupBox_3);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(10, 160, 46, 14));
        label_20 = new QLabel(groupBox_3);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 200, 61, 16));
        label_21 = new QLabel(groupBox_3);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 220, 61, 16));
        groupBox_4 = new QGroupBox(DetectorTab);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(40, 300, 231, 181));
        DefectEdt = new QTextEdit(groupBox_4);
        DefectEdt->setObjectName(QString::fromUtf8("DefectEdt"));
        DefectEdt->setGeometry(QRect(80, 30, 131, 121));
        DefectEdt->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        Gain1Edt = new QLineEdit(DetectorTab);
        Gain1Edt->setObjectName(QString::fromUtf8("Gain1Edt"));
        Gain1Edt->setGeometry(QRect(430, 340, 113, 20));
        Gain2Edt = new QLineEdit(DetectorTab);
        Gain2Edt->setObjectName(QString::fromUtf8("Gain2Edt"));
        Gain2Edt->setGeometry(QRect(430, 360, 113, 20));
        Offset1Edt = new QLineEdit(DetectorTab);
        Offset1Edt->setObjectName(QString::fromUtf8("Offset1Edt"));
        Offset1Edt->setGeometry(QRect(430, 400, 113, 20));
        Offset2Edt = new QLineEdit(DetectorTab);
        Offset2Edt->setObjectName(QString::fromUtf8("Offset2Edt"));
        Offset2Edt->setGeometry(QRect(430, 420, 113, 20));
        ExtOffsetEdt = new QLineEdit(DetectorTab);
        ExtOffsetEdt->setObjectName(QString::fromUtf8("ExtOffsetEdt"));
        ExtOffsetEdt->setGeometry(QRect(430, 460, 113, 20));
        label_4 = new QLabel(DetectorTab);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(40, 40, 46, 14));
        label_5 = new QLabel(DetectorTab);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(40, 70, 71, 16));
        label_22 = new QLabel(DetectorTab);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(360, 340, 46, 14));
        label_23 = new QLabel(DetectorTab);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(360, 360, 46, 14));
        label_24 = new QLabel(DetectorTab);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(360, 400, 46, 14));
        label_25 = new QLabel(DetectorTab);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(360, 420, 46, 14));
        label_26 = new QLabel(DetectorTab);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(360, 460, 71, 16));
        tabWidget->addTab(DetectorTab, QString());
        StandaloneTab = new QWidget();
        StandaloneTab->setObjectName(QString::fromUtf8("StandaloneTab"));
        EnableStandAloneChk = new QCheckBox(StandaloneTab);
        EnableStandAloneChk->setObjectName(QString::fromUtf8("EnableStandAloneChk"));
        EnableStandAloneChk->setGeometry(QRect(30, 10, 72, 18));
        groupBox_5 = new QGroupBox(StandaloneTab);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(20, 40, 461, 371));
        groupBox_8 = new QGroupBox(groupBox_5);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(220, 220, 231, 131));
        FlashesPerScanEdt = new QLineEdit(groupBox_8);
        FlashesPerScanEdt->setObjectName(QString::fromUtf8("FlashesPerScanEdt"));
        FlashesPerScanEdt->setGeometry(QRect(150, 20, 71, 20));
        LaserDelayEdt = new QLineEdit(groupBox_8);
        LaserDelayEdt->setObjectName(QString::fromUtf8("LaserDelayEdt"));
        LaserDelayEdt->setGeometry(QRect(150, 40, 71, 20));
        LaserWidtEdt = new QLineEdit(groupBox_8);
        LaserWidtEdt->setObjectName(QString::fromUtf8("LaserWidtEdt"));
        LaserWidtEdt->setGeometry(QRect(150, 60, 71, 20));
        LaserWavEdt = new QLineEdit(groupBox_8);
        LaserWavEdt->setObjectName(QString::fromUtf8("LaserWavEdt"));
        LaserWavEdt->setGeometry(QRect(150, 80, 71, 20));
        StoreToRamEdt = new QLineEdit(groupBox_8);
        StoreToRamEdt->setObjectName(QString::fromUtf8("StoreToRamEdt"));
        StoreToRamEdt->setGeometry(QRect(150, 100, 71, 20));
        label_38 = new QLabel(groupBox_8);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(10, 20, 111, 16));
        label_39 = new QLabel(groupBox_8);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(10, 40, 101, 16));
        label_40 = new QLabel(groupBox_8);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(10, 60, 111, 16));
        label_41 = new QLabel(groupBox_8);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(10, 80, 141, 16));
        label_42 = new QLabel(groupBox_8);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(10, 100, 111, 16));
        groupBox_9 = new QGroupBox(groupBox_5);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(230, 40, 221, 71));
        DarkPercentageEdt = new QLineEdit(groupBox_9);
        DarkPercentageEdt->setObjectName(QString::fromUtf8("DarkPercentageEdt"));
        DarkPercentageEdt->setGeometry(QRect(10, 40, 51, 20));
        DarkCorrEnableChk = new QCheckBox(groupBox_9);
        DarkCorrEnableChk->setObjectName(QString::fromUtf8("DarkCorrEnableChk"));
        DarkCorrEnableChk->setGeometry(QRect(10, 20, 72, 18));
        label_54 = new QLabel(groupBox_9);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(70, 40, 46, 14));
        StartPixelEdt = new QLineEdit(groupBox_5);
        StartPixelEdt->setObjectName(QString::fromUtf8("StartPixelEdt"));
        StartPixelEdt->setGeometry(QRect(150, 40, 71, 20));
        StopPixelEdt = new QLineEdit(groupBox_5);
        StopPixelEdt->setObjectName(QString::fromUtf8("StopPixelEdt"));
        StopPixelEdt->setGeometry(QRect(150, 60, 71, 20));
        IntTimeEdt = new QLineEdit(groupBox_5);
        IntTimeEdt->setObjectName(QString::fromUtf8("IntTimeEdt"));
        IntTimeEdt->setGeometry(QRect(150, 80, 71, 20));
        IntDelayEdt = new QLineEdit(groupBox_5);
        IntDelayEdt->setObjectName(QString::fromUtf8("IntDelayEdt"));
        IntDelayEdt->setGeometry(QRect(150, 100, 71, 20));
        NrAveragesEdt = new QLineEdit(groupBox_5);
        NrAveragesEdt->setObjectName(QString::fromUtf8("NrAveragesEdt"));
        NrAveragesEdt->setGeometry(QRect(150, 120, 71, 20));
        SatDetectEdt = new QLineEdit(groupBox_5);
        SatDetectEdt->setObjectName(QString::fromUtf8("SatDetectEdt"));
        SatDetectEdt->setGeometry(QRect(150, 140, 71, 20));
        label_6 = new QLabel(groupBox_5);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 40, 111, 16));
        label_27 = new QLabel(groupBox_5);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(10, 60, 101, 16));
        label_28 = new QLabel(groupBox_5);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 80, 141, 16));
        label_29 = new QLabel(groupBox_5);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(10, 100, 141, 16));
        label_30 = new QLabel(groupBox_5);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(10, 120, 131, 16));
        label_31 = new QLabel(groupBox_5);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(10, 140, 131, 16));
        groupBox_11 = new QGroupBox(groupBox_5);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(230, 130, 221, 71));
        SmoothModelEdt = new QLineEdit(groupBox_11);
        SmoothModelEdt->setObjectName(QString::fromUtf8("SmoothModelEdt"));
        SmoothModelEdt->setGeometry(QRect(130, 20, 71, 20));
        SmoothPixelsEdt = new QLineEdit(groupBox_11);
        SmoothPixelsEdt->setObjectName(QString::fromUtf8("SmoothPixelsEdt"));
        SmoothPixelsEdt->setGeometry(QRect(130, 40, 71, 20));
        label_35 = new QLabel(groupBox_11);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(10, 20, 81, 16));
        label_36 = new QLabel(groupBox_11);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(80, 70, 46, 14));
        label_37 = new QLabel(groupBox_11);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(10, 40, 81, 16));
        groupBox_7 = new QGroupBox(groupBox_5);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(10, 170, 201, 181));
        groupBox_18 = new QGroupBox(groupBox_7);
        groupBox_18->setObjectName(QString::fromUtf8("groupBox_18"));
        groupBox_18->setGeometry(QRect(10, 20, 181, 51));
        HardwareTriggerRBtn = new QRadioButton(groupBox_18);
        HardwareTriggerRBtn->setObjectName(QString::fromUtf8("HardwareTriggerRBtn"));
        HardwareTriggerRBtn->setGeometry(QRect(90, 10, 84, 18));
        SoftwareTriggerRBtn = new QRadioButton(groupBox_18);
        SoftwareTriggerRBtn->setObjectName(QString::fromUtf8("SoftwareTriggerRBtn"));
        SoftwareTriggerRBtn->setGeometry(QRect(90, 20, 84, 31));
        groupBox_19 = new QGroupBox(groupBox_7);
        groupBox_19->setObjectName(QString::fromUtf8("groupBox_19"));
        groupBox_19->setGeometry(QRect(10, 70, 181, 51));
        ExternalTriggerRbtn = new QRadioButton(groupBox_19);
        ExternalTriggerRbtn->setObjectName(QString::fromUtf8("ExternalTriggerRbtn"));
        ExternalTriggerRbtn->setGeometry(QRect(90, 10, 84, 18));
        SynchTriggerRBtn = new QRadioButton(groupBox_19);
        SynchTriggerRBtn->setObjectName(QString::fromUtf8("SynchTriggerRBtn"));
        SynchTriggerRBtn->setGeometry(QRect(90, 30, 84, 18));
        groupBox_21 = new QGroupBox(groupBox_7);
        groupBox_21->setObjectName(QString::fromUtf8("groupBox_21"));
        groupBox_21->setGeometry(QRect(10, 120, 181, 51));
        EdgeTriggerRBtn = new QRadioButton(groupBox_21);
        EdgeTriggerRBtn->setObjectName(QString::fromUtf8("EdgeTriggerRBtn"));
        EdgeTriggerRBtn->setGeometry(QRect(90, 10, 84, 18));
        LevelTriggerRBtn = new QRadioButton(groupBox_21);
        LevelTriggerRBtn->setObjectName(QString::fromUtf8("LevelTriggerRBtn"));
        LevelTriggerRBtn->setGeometry(QRect(90, 30, 84, 18));
        groupBox_6 = new QGroupBox(StandaloneTab);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(500, 40, 231, 371));
        groupBox_10 = new QGroupBox(groupBox_6);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(20, 80, 191, 271));
        GetTimeStampChk = new QCheckBox(groupBox_10);
        GetTimeStampChk->setObjectName(QString::fromUtf8("GetTimeStampChk"));
        GetTimeStampChk->setGeometry(QRect(10, 20, 181, 18));
        DateNrEdt = new QLineEdit(groupBox_10);
        DateNrEdt->setObjectName(QString::fromUtf8("DateNrEdt"));
        DateNrEdt->setGeometry(QRect(70, 40, 113, 20));
        TimeNrEdt = new QLineEdit(groupBox_10);
        TimeNrEdt->setObjectName(QString::fromUtf8("TimeNrEdt"));
        TimeNrEdt->setGeometry(QRect(70, 140, 113, 20));
        DayEdt = new QLineEdit(groupBox_10);
        DayEdt->setObjectName(QString::fromUtf8("DayEdt"));
        DayEdt->setGeometry(QRect(140, 60, 41, 20));
        MonthEdt = new QLineEdit(groupBox_10);
        MonthEdt->setObjectName(QString::fromUtf8("MonthEdt"));
        MonthEdt->setGeometry(QRect(140, 80, 41, 20));
        YearEdt = new QLineEdit(groupBox_10);
        YearEdt->setObjectName(QString::fromUtf8("YearEdt"));
        YearEdt->setGeometry(QRect(140, 100, 41, 20));
        SecEdt = new QLineEdit(groupBox_10);
        SecEdt->setObjectName(QString::fromUtf8("SecEdt"));
        SecEdt->setGeometry(QRect(140, 160, 41, 20));
        MinEdt = new QLineEdit(groupBox_10);
        MinEdt->setObjectName(QString::fromUtf8("MinEdt"));
        MinEdt->setGeometry(QRect(140, 180, 41, 20));
        HourEdt = new QLineEdit(groupBox_10);
        HourEdt->setObjectName(QString::fromUtf8("HourEdt"));
        HourEdt->setGeometry(QRect(140, 200, 41, 20));
        label_46 = new QLabel(groupBox_10);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(10, 40, 46, 14));
        label_47 = new QLabel(groupBox_10);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(20, 60, 91, 16));
        label_48 = new QLabel(groupBox_10);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(20, 80, 101, 16));
        label_49 = new QLabel(groupBox_10);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(20, 100, 91, 16));
        label_50 = new QLabel(groupBox_10);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(10, 140, 46, 14));
        label_51 = new QLabel(groupBox_10);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(20, 160, 101, 16));
        label_52 = new QLabel(groupBox_10);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(20, 180, 101, 16));
        label_53 = new QLabel(groupBox_10);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(20, 200, 101, 16));
        SDCardEnableChk = new QCheckBox(groupBox_6);
        SDCardEnableChk->setObjectName(QString::fromUtf8("SDCardEnableChk"));
        SDCardEnableChk->setGeometry(QRect(10, 20, 72, 18));
        SpectrumTypeEdt = new QLineEdit(groupBox_6);
        SpectrumTypeEdt->setObjectName(QString::fromUtf8("SpectrumTypeEdt"));
        SpectrumTypeEdt->setGeometry(QRect(140, 40, 51, 20));
        FileRootNameEdt = new QLineEdit(groupBox_6);
        FileRootNameEdt->setObjectName(QString::fromUtf8("FileRootNameEdt"));
        FileRootNameEdt->setGeometry(QRect(140, 60, 51, 20));
        label_44 = new QLabel(groupBox_6);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(10, 40, 101, 16));
        label_45 = new QLabel(groupBox_6);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(10, 60, 111, 16));
        NrMeasEdt = new QLineEdit(StandaloneTab);
        NrMeasEdt->setObjectName(QString::fromUtf8("NrMeasEdt"));
        NrMeasEdt->setGeometry(QRect(150, 430, 61, 20));
        label_43 = new QLabel(StandaloneTab);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(20, 430, 131, 16));
        tabWidget->addTab(StandaloneTab, QString());
        IrradianceTab = new QWidget();
        IrradianceTab->setObjectName(QString::fromUtf8("IrradianceTab"));
        groupBox_12 = new QGroupBox(IrradianceTab);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(20, 20, 261, 451));
        groupBox_13 = new QGroupBox(groupBox_12);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(20, 310, 211, 80));
        IrradianceSmoothModelEdt = new QLineEdit(groupBox_13);
        IrradianceSmoothModelEdt->setObjectName(QString::fromUtf8("IrradianceSmoothModelEdt"));
        IrradianceSmoothModelEdt->setGeometry(QRect(90, 20, 61, 20));
        IrradianceSmoothPixelsEdt = new QLineEdit(groupBox_13);
        IrradianceSmoothPixelsEdt->setObjectName(QString::fromUtf8("IrradianceSmoothPixelsEdt"));
        IrradianceSmoothPixelsEdt->setGeometry(QRect(90, 50, 61, 20));
        label_55 = new QLabel(groupBox_13);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(10, 20, 61, 16));
        label_56 = new QLabel(groupBox_13);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(10, 50, 71, 16));
        IrradianceConvEdt = new QTextEdit(groupBox_12);
        IrradianceConvEdt->setObjectName(QString::fromUtf8("IrradianceConvEdt"));
        IrradianceConvEdt->setGeometry(QRect(20, 20, 161, 251));
        IrradianceConvEdt->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        IrradianceIntTimeEdt = new QLineEdit(groupBox_12);
        IrradianceIntTimeEdt->setObjectName(QString::fromUtf8("IrradianceIntTimeEdt"));
        IrradianceIntTimeEdt->setGeometry(QRect(150, 410, 61, 20));
        label_57 = new QLabel(groupBox_12);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(20, 400, 111, 41));
        label_57->setWordWrap(true);
        IrradCalibrationTypeEdt = new QLineEdit(IrradianceTab);
        IrradCalibrationTypeEdt->setObjectName(QString::fromUtf8("IrradCalibrationTypeEdt"));
        IrradCalibrationTypeEdt->setGeometry(QRect(530, 40, 113, 20));
        IrradFiberDiameterEdt = new QLineEdit(IrradianceTab);
        IrradFiberDiameterEdt->setObjectName(QString::fromUtf8("IrradFiberDiameterEdt"));
        IrradFiberDiameterEdt->setGeometry(QRect(530, 80, 113, 20));
        label_58 = new QLabel(IrradianceTab);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(310, 40, 171, 16));
        label_59 = new QLabel(IrradianceTab);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(310, 80, 211, 16));
        tabWidget->addTab(IrradianceTab, QString());
        ReflectanceTab = new QWidget();
        ReflectanceTab->setObjectName(QString::fromUtf8("ReflectanceTab"));
        groupBox_14 = new QGroupBox(ReflectanceTab);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(20, 20, 261, 451));
        groupBox_15 = new QGroupBox(groupBox_14);
        groupBox_15->setObjectName(QString::fromUtf8("groupBox_15"));
        groupBox_15->setGeometry(QRect(20, 310, 221, 80));
        ReflectanceSmoothModelEdt = new QLineEdit(groupBox_15);
        ReflectanceSmoothModelEdt->setObjectName(QString::fromUtf8("ReflectanceSmoothModelEdt"));
        ReflectanceSmoothModelEdt->setGeometry(QRect(90, 20, 61, 20));
        ReflectanceSmoothPixelsEdt = new QLineEdit(groupBox_15);
        ReflectanceSmoothPixelsEdt->setObjectName(QString::fromUtf8("ReflectanceSmoothPixelsEdt"));
        ReflectanceSmoothPixelsEdt->setGeometry(QRect(90, 50, 61, 20));
        label_60 = new QLabel(groupBox_15);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(10, 20, 61, 16));
        label_61 = new QLabel(groupBox_15);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(10, 50, 71, 16));
        ReflectanceCorrEdt = new QTextEdit(groupBox_14);
        ReflectanceCorrEdt->setObjectName(QString::fromUtf8("ReflectanceCorrEdt"));
        ReflectanceCorrEdt->setGeometry(QRect(20, 20, 161, 251));
        ReflectanceCorrEdt->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        ReflectanceIntTimeEdt = new QLineEdit(groupBox_14);
        ReflectanceIntTimeEdt->setObjectName(QString::fromUtf8("ReflectanceIntTimeEdt"));
        ReflectanceIntTimeEdt->setGeometry(QRect(160, 410, 61, 20));
        label_62 = new QLabel(groupBox_14);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(20, 400, 111, 41));
        label_62->setWordWrap(true);
        tabWidget->addTab(ReflectanceTab, QString());
        SpectrumTab = new QWidget();
        SpectrumTab->setObjectName(QString::fromUtf8("SpectrumTab"));
        groupBox_16 = new QGroupBox(SpectrumTab);
        groupBox_16->setObjectName(QString::fromUtf8("groupBox_16"));
        groupBox_16->setGeometry(QRect(20, 20, 261, 451));
        SpectrumCorrEdt = new QTextEdit(groupBox_16);
        SpectrumCorrEdt->setObjectName(QString::fromUtf8("SpectrumCorrEdt"));
        SpectrumCorrEdt->setGeometry(QRect(20, 20, 161, 381));
        SpectrumCorrEdt->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        tabWidget->addTab(SpectrumTab, QString());
        TemperatureTab = new QWidget();
        TemperatureTab->setObjectName(QString::fromUtf8("TemperatureTab"));
        groupBox_17 = new QGroupBox(TemperatureTab);
        groupBox_17->setObjectName(QString::fromUtf8("groupBox_17"));
        groupBox_17->setGeometry(QRect(20, 70, 201, 131));
        NTC1X0Edt = new QLineEdit(groupBox_17);
        NTC1X0Edt->setObjectName(QString::fromUtf8("NTC1X0Edt"));
        NTC1X0Edt->setGeometry(QRect(70, 20, 113, 20));
        NTC1X1Edt = new QLineEdit(groupBox_17);
        NTC1X1Edt->setObjectName(QString::fromUtf8("NTC1X1Edt"));
        NTC1X1Edt->setGeometry(QRect(70, 40, 113, 20));
        NTC1X3Edt = new QLineEdit(groupBox_17);
        NTC1X3Edt->setObjectName(QString::fromUtf8("NTC1X3Edt"));
        NTC1X3Edt->setGeometry(QRect(70, 80, 113, 20));
        NTC1X4Edt = new QLineEdit(groupBox_17);
        NTC1X4Edt->setObjectName(QString::fromUtf8("NTC1X4Edt"));
        NTC1X4Edt->setGeometry(QRect(70, 100, 113, 20));
        NTC1X2Edt = new QLineEdit(groupBox_17);
        NTC1X2Edt->setObjectName(QString::fromUtf8("NTC1X2Edt"));
        NTC1X2Edt->setGeometry(QRect(70, 60, 113, 20));
        label_63 = new QLabel(groupBox_17);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(10, 20, 61, 16));
        label_64 = new QLabel(groupBox_17);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(10, 40, 46, 14));
        label_65 = new QLabel(groupBox_17);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(10, 60, 46, 14));
        label_66 = new QLabel(groupBox_17);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(10, 80, 46, 14));
        label_67 = new QLabel(groupBox_17);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(10, 100, 46, 14));
        groupBox_20 = new QGroupBox(TemperatureTab);
        groupBox_20->setObjectName(QString::fromUtf8("groupBox_20"));
        groupBox_20->setGeometry(QRect(240, 70, 201, 131));
        NTC2X0Edt = new QLineEdit(groupBox_20);
        NTC2X0Edt->setObjectName(QString::fromUtf8("NTC2X0Edt"));
        NTC2X0Edt->setGeometry(QRect(70, 20, 113, 20));
        NTC2X1Edt = new QLineEdit(groupBox_20);
        NTC2X1Edt->setObjectName(QString::fromUtf8("NTC2X1Edt"));
        NTC2X1Edt->setGeometry(QRect(70, 40, 113, 20));
        NTC2X3Edt = new QLineEdit(groupBox_20);
        NTC2X3Edt->setObjectName(QString::fromUtf8("NTC2X3Edt"));
        NTC2X3Edt->setGeometry(QRect(70, 80, 113, 20));
        NTC2X4Edt = new QLineEdit(groupBox_20);
        NTC2X4Edt->setObjectName(QString::fromUtf8("NTC2X4Edt"));
        NTC2X4Edt->setGeometry(QRect(70, 100, 113, 20));
        NTC2X2Edt = new QLineEdit(groupBox_20);
        NTC2X2Edt->setObjectName(QString::fromUtf8("NTC2X2Edt"));
        NTC2X2Edt->setGeometry(QRect(70, 60, 113, 20));
        label_78 = new QLabel(groupBox_20);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(10, 20, 61, 16));
        label_79 = new QLabel(groupBox_20);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(10, 40, 46, 14));
        label_80 = new QLabel(groupBox_20);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(10, 60, 46, 14));
        label_81 = new QLabel(groupBox_20);
        label_81->setObjectName(QString::fromUtf8("label_81"));
        label_81->setGeometry(QRect(10, 80, 46, 14));
        label_82 = new QLabel(groupBox_20);
        label_82->setObjectName(QString::fromUtf8("label_82"));
        label_82->setGeometry(QRect(10, 100, 46, 14));
        groupBox_23 = new QGroupBox(TemperatureTab);
        groupBox_23->setObjectName(QString::fromUtf8("groupBox_23"));
        groupBox_23->setGeometry(QRect(460, 70, 201, 131));
        ThermistorX0Edt = new QLineEdit(groupBox_23);
        ThermistorX0Edt->setObjectName(QString::fromUtf8("ThermistorX0Edt"));
        ThermistorX0Edt->setGeometry(QRect(70, 20, 113, 20));
        ThermistorX1Edt = new QLineEdit(groupBox_23);
        ThermistorX1Edt->setObjectName(QString::fromUtf8("ThermistorX1Edt"));
        ThermistorX1Edt->setGeometry(QRect(70, 40, 113, 20));
        ThermistorX3Edt = new QLineEdit(groupBox_23);
        ThermistorX3Edt->setObjectName(QString::fromUtf8("ThermistorX3Edt"));
        ThermistorX3Edt->setGeometry(QRect(70, 80, 113, 20));
        ThermistorX4Edt = new QLineEdit(groupBox_23);
        ThermistorX4Edt->setObjectName(QString::fromUtf8("ThermistorX4Edt"));
        ThermistorX4Edt->setGeometry(QRect(70, 100, 113, 20));
        ThermistorX2Edt = new QLineEdit(groupBox_23);
        ThermistorX2Edt->setObjectName(QString::fromUtf8("ThermistorX2Edt"));
        ThermistorX2Edt->setGeometry(QRect(70, 60, 113, 20));
        label_93 = new QLabel(groupBox_23);
        label_93->setObjectName(QString::fromUtf8("label_93"));
        label_93->setGeometry(QRect(10, 20, 61, 16));
        label_94 = new QLabel(groupBox_23);
        label_94->setObjectName(QString::fromUtf8("label_94"));
        label_94->setGeometry(QRect(10, 40, 46, 14));
        label_95 = new QLabel(groupBox_23);
        label_95->setObjectName(QString::fromUtf8("label_95"));
        label_95->setGeometry(QRect(10, 60, 46, 14));
        label_96 = new QLabel(groupBox_23);
        label_96->setObjectName(QString::fromUtf8("label_96"));
        label_96->setGeometry(QRect(10, 80, 46, 14));
        label_97 = new QLabel(groupBox_23);
        label_97->setObjectName(QString::fromUtf8("label_97"));
        label_97->setGeometry(QRect(10, 100, 46, 14));
        tabWidget->addTab(TemperatureTab, QString());
        TecTab = new QWidget();
        TecTab->setObjectName(QString::fromUtf8("TecTab"));
        groupBox_24 = new QGroupBox(TecTab);
        groupBox_24->setObjectName(QString::fromUtf8("groupBox_24"));
        groupBox_24->setGeometry(QRect(20, 110, 191, 111));
        TECX0Edt = new QLineEdit(groupBox_24);
        TECX0Edt->setObjectName(QString::fromUtf8("TECX0Edt"));
        TECX0Edt->setGeometry(QRect(120, 30, 51, 20));
        TECX1Edt = new QLineEdit(groupBox_24);
        TECX1Edt->setObjectName(QString::fromUtf8("TECX1Edt"));
        TECX1Edt->setGeometry(QRect(120, 70, 51, 20));
        label_99 = new QLabel(groupBox_24);
        label_99->setObjectName(QString::fromUtf8("label_99"));
        label_99->setGeometry(QRect(20, 30, 46, 14));
        label_100 = new QLabel(groupBox_24);
        label_100->setObjectName(QString::fromUtf8("label_100"));
        label_100->setGeometry(QRect(20, 70, 46, 14));
        TECEnableChk = new QCheckBox(TecTab);
        TECEnableChk->setObjectName(QString::fromUtf8("TECEnableChk"));
        TECEnableChk->setGeometry(QRect(20, 40, 72, 18));
        SetPointEdt = new QLineEdit(TecTab);
        SetPointEdt->setObjectName(QString::fromUtf8("SetPointEdt"));
        SetPointEdt->setGeometry(QRect(160, 70, 51, 20));
        label_98 = new QLabel(TecTab);
        label_98->setObjectName(QString::fromUtf8("label_98"));
        label_98->setGeometry(QRect(20, 70, 131, 16));
        tabWidget->addTab(TecTab, QString());
        StrucLengthEdt = new QLineEdit(Eeprom);
        StrucLengthEdt->setObjectName(QString::fromUtf8("StrucLengthEdt"));
        StrucLengthEdt->setGeometry(QRect(190, 20, 113, 20));
        StrucVersionEdt = new QLineEdit(Eeprom);
        StrucVersionEdt->setObjectName(QString::fromUtf8("StrucVersionEdt"));
        StrucVersionEdt->setGeometry(QRect(190, 50, 113, 20));
        FriendlyEdt = new QLineEdit(Eeprom);
        FriendlyEdt->setObjectName(QString::fromUtf8("FriendlyEdt"));
        FriendlyEdt->setGeometry(QRect(190, 80, 621, 20));
        label = new QLabel(Eeprom);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(30, 20, 151, 16));
        label_2 = new QLabel(Eeprom);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(30, 50, 121, 16));
        label_3 = new QLabel(Eeprom);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(30, 80, 101, 16));
        QWidget::setTabOrder(StrucLengthEdt, StrucVersionEdt);
        QWidget::setTabOrder(StrucVersionEdt, FriendlyEdt);
        QWidget::setTabOrder(FriendlyEdt, tabWidget);
        QWidget::setTabOrder(tabWidget, SensorComboBox);
        QWidget::setTabOrder(SensorComboBox, NrPixelsEdt);
        QWidget::setTabOrder(NrPixelsEdt, WavCalInterceptEdt);
        QWidget::setTabOrder(WavCalInterceptEdt, WavCalX1Edt);
        QWidget::setTabOrder(WavCalX1Edt, WavCalX2Edt);
        QWidget::setTabOrder(WavCalX2Edt, WavCalX3Edt);
        QWidget::setTabOrder(WavCalX3Edt, WavCalX4Edt);
        QWidget::setTabOrder(WavCalX4Edt, DefectEdt);
        QWidget::setTabOrder(DefectEdt, NonLinInterceptEdt);
        QWidget::setTabOrder(NonLinInterceptEdt, NonLinX1Edt);
        QWidget::setTabOrder(NonLinX1Edt, NonLinX2Edt);
        QWidget::setTabOrder(NonLinX2Edt, NonLinX3Edt);
        QWidget::setTabOrder(NonLinX3Edt, NonLinX4Edt);
        QWidget::setTabOrder(NonLinX4Edt, NonLinX5Edt);
        QWidget::setTabOrder(NonLinX5Edt, NonLinX6Edt);
        QWidget::setTabOrder(NonLinX6Edt, NonLinX7Edt);
        QWidget::setTabOrder(NonLinX7Edt, LoCountsEdt);
        QWidget::setTabOrder(LoCountsEdt, HiCountsEdt);
        QWidget::setTabOrder(HiCountsEdt, NonLinEnableChk);
        QWidget::setTabOrder(NonLinEnableChk, Gain1Edt);
        QWidget::setTabOrder(Gain1Edt, Gain2Edt);
        QWidget::setTabOrder(Gain2Edt, Offset1Edt);
        QWidget::setTabOrder(Offset1Edt, Offset2Edt);
        QWidget::setTabOrder(Offset2Edt, ExtOffsetEdt);
        QWidget::setTabOrder(ExtOffsetEdt, SaveEepromBtn);
        QWidget::setTabOrder(SaveEepromBtn, CancelEepromBtn);
        QWidget::setTabOrder(CancelEepromBtn, EnableStandAloneChk);
        QWidget::setTabOrder(EnableStandAloneChk, StartPixelEdt);
        QWidget::setTabOrder(StartPixelEdt, StopPixelEdt);
        QWidget::setTabOrder(StopPixelEdt, IntTimeEdt);
        QWidget::setTabOrder(IntTimeEdt, IntDelayEdt);
        QWidget::setTabOrder(IntDelayEdt, NrAveragesEdt);
        QWidget::setTabOrder(NrAveragesEdt, SatDetectEdt);
        QWidget::setTabOrder(SatDetectEdt, HardwareTriggerRBtn);
        QWidget::setTabOrder(HardwareTriggerRBtn, SoftwareTriggerRBtn);
        QWidget::setTabOrder(SoftwareTriggerRBtn, ExternalTriggerRbtn);
        QWidget::setTabOrder(ExternalTriggerRbtn, SynchTriggerRBtn);
        QWidget::setTabOrder(SynchTriggerRBtn, EdgeTriggerRBtn);
        QWidget::setTabOrder(EdgeTriggerRBtn, LevelTriggerRBtn);
        QWidget::setTabOrder(LevelTriggerRBtn, NrMeasEdt);
        QWidget::setTabOrder(NrMeasEdt, DarkCorrEnableChk);
        QWidget::setTabOrder(DarkCorrEnableChk, DarkPercentageEdt);
        QWidget::setTabOrder(DarkPercentageEdt, SmoothModelEdt);
        QWidget::setTabOrder(SmoothModelEdt, SmoothPixelsEdt);
        QWidget::setTabOrder(SmoothPixelsEdt, FlashesPerScanEdt);
        QWidget::setTabOrder(FlashesPerScanEdt, LaserDelayEdt);
        QWidget::setTabOrder(LaserDelayEdt, LaserWidtEdt);
        QWidget::setTabOrder(LaserWidtEdt, LaserWavEdt);
        QWidget::setTabOrder(LaserWavEdt, StoreToRamEdt);
        QWidget::setTabOrder(StoreToRamEdt, SDCardEnableChk);
        QWidget::setTabOrder(SDCardEnableChk, SpectrumTypeEdt);
        QWidget::setTabOrder(SpectrumTypeEdt, FileRootNameEdt);
        QWidget::setTabOrder(FileRootNameEdt, GetTimeStampChk);
        QWidget::setTabOrder(GetTimeStampChk, DateNrEdt);
        QWidget::setTabOrder(DateNrEdt, DayEdt);
        QWidget::setTabOrder(DayEdt, MonthEdt);
        QWidget::setTabOrder(MonthEdt, YearEdt);
        QWidget::setTabOrder(YearEdt, TimeNrEdt);
        QWidget::setTabOrder(TimeNrEdt, SecEdt);
        QWidget::setTabOrder(SecEdt, MinEdt);
        QWidget::setTabOrder(MinEdt, HourEdt);
        QWidget::setTabOrder(HourEdt, IrradianceConvEdt);
        QWidget::setTabOrder(IrradianceConvEdt, IrradianceSmoothModelEdt);
        QWidget::setTabOrder(IrradianceSmoothModelEdt, IrradianceSmoothPixelsEdt);
        QWidget::setTabOrder(IrradianceSmoothPixelsEdt, IrradianceIntTimeEdt);
        QWidget::setTabOrder(IrradianceIntTimeEdt, IrradCalibrationTypeEdt);
        QWidget::setTabOrder(IrradCalibrationTypeEdt, IrradFiberDiameterEdt);
        QWidget::setTabOrder(IrradFiberDiameterEdt, ReflectanceCorrEdt);
        QWidget::setTabOrder(ReflectanceCorrEdt, ReflectanceSmoothModelEdt);
        QWidget::setTabOrder(ReflectanceSmoothModelEdt, ReflectanceSmoothPixelsEdt);
        QWidget::setTabOrder(ReflectanceSmoothPixelsEdt, ReflectanceIntTimeEdt);
        QWidget::setTabOrder(ReflectanceIntTimeEdt, SpectrumCorrEdt);
        QWidget::setTabOrder(SpectrumCorrEdt, NTC1X0Edt);
        QWidget::setTabOrder(NTC1X0Edt, NTC1X1Edt);
        QWidget::setTabOrder(NTC1X1Edt, NTC1X2Edt);
        QWidget::setTabOrder(NTC1X2Edt, NTC1X3Edt);
        QWidget::setTabOrder(NTC1X3Edt, NTC1X4Edt);
        QWidget::setTabOrder(NTC1X4Edt, NTC2X0Edt);
        QWidget::setTabOrder(NTC2X0Edt, NTC2X1Edt);
        QWidget::setTabOrder(NTC2X1Edt, NTC2X2Edt);
        QWidget::setTabOrder(NTC2X2Edt, NTC2X3Edt);
        QWidget::setTabOrder(NTC2X3Edt, NTC2X4Edt);
        QWidget::setTabOrder(NTC2X4Edt, ThermistorX0Edt);
        QWidget::setTabOrder(ThermistorX0Edt, ThermistorX1Edt);
        QWidget::setTabOrder(ThermistorX1Edt, ThermistorX2Edt);
        QWidget::setTabOrder(ThermistorX2Edt, ThermistorX3Edt);
        QWidget::setTabOrder(ThermistorX3Edt, ThermistorX4Edt);
        QWidget::setTabOrder(ThermistorX4Edt, TECEnableChk);
        QWidget::setTabOrder(TECEnableChk, SetPointEdt);
        QWidget::setTabOrder(SetPointEdt, TECX0Edt);
        QWidget::setTabOrder(TECX0Edt, TECX1Edt);

        retranslateUi(Eeprom);
        QObject::connect(CancelEepromBtn, SIGNAL(clicked()), Eeprom, SLOT(reject()));
        QObject::connect(SaveEepromBtn, SIGNAL(clicked()), Eeprom, SLOT(accept()));

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Eeprom);
    } // setupUi

    void retranslateUi(QDialog *Eeprom)
    {
        Eeprom->setWindowTitle(QCoreApplication::translate("Eeprom", "Eeprom settings", nullptr));
        SaveEepromBtn->setText(QCoreApplication::translate("Eeprom", "Save to EEPROM", nullptr));
        CancelEepromBtn->setText(QCoreApplication::translate("Eeprom", "Cancel", nullptr));
        groupBox->setTitle(QCoreApplication::translate("Eeprom", "Wavelength Calibration", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("Eeprom", "GroupBox", nullptr));
        label_7->setText(QCoreApplication::translate("Eeprom", "Intercept", nullptr));
        label_8->setText(QCoreApplication::translate("Eeprom", "X1", nullptr));
        label_9->setText(QCoreApplication::translate("Eeprom", "X2", nullptr));
        label_10->setText(QCoreApplication::translate("Eeprom", "X3", nullptr));
        label_11->setText(QCoreApplication::translate("Eeprom", "X4", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("Eeprom", "Nonlinearity Calibration", nullptr));
        NonLinEnableChk->setText(QCoreApplication::translate("Eeprom", "Enable Nonlinearity Correction", nullptr));
        label_12->setText(QCoreApplication::translate("Eeprom", "Intercept", nullptr));
        label_13->setText(QCoreApplication::translate("Eeprom", "X1", nullptr));
        label_14->setText(QCoreApplication::translate("Eeprom", "X2", nullptr));
        label_15->setText(QCoreApplication::translate("Eeprom", "X3", nullptr));
        label_16->setText(QCoreApplication::translate("Eeprom", "X4", nullptr));
        label_17->setText(QCoreApplication::translate("Eeprom", "X5", nullptr));
        label_18->setText(QCoreApplication::translate("Eeprom", "X6", nullptr));
        label_19->setText(QCoreApplication::translate("Eeprom", "X7", nullptr));
        label_20->setText(QCoreApplication::translate("Eeprom", "LoCounts", nullptr));
        label_21->setText(QCoreApplication::translate("Eeprom", "HiCounts", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("Eeprom", "Defective Pixels", nullptr));
        label_4->setText(QCoreApplication::translate("Eeprom", "Sensor", nullptr));
        label_5->setText(QCoreApplication::translate("Eeprom", "Nr of Pixels", nullptr));
        label_22->setText(QCoreApplication::translate("Eeprom", "Gain1", nullptr));
        label_23->setText(QCoreApplication::translate("Eeprom", "Gain2", nullptr));
        label_24->setText(QCoreApplication::translate("Eeprom", "Offset1", nullptr));
        label_25->setText(QCoreApplication::translate("Eeprom", "Offset2", nullptr));
        label_26->setText(QCoreApplication::translate("Eeprom", "Ext. Offset", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(DetectorTab), QCoreApplication::translate("Eeprom", "Detector", nullptr));
        EnableStandAloneChk->setText(QCoreApplication::translate("Eeprom", "Enable", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("Eeprom", "Measurement Settings", nullptr));
        groupBox_8->setTitle(QCoreApplication::translate("Eeprom", "Control Settings", nullptr));
        label_38->setText(QCoreApplication::translate("Eeprom", "Flashes per Scan", nullptr));
        label_39->setText(QCoreApplication::translate("Eeprom", "Laser Delay [ns]", nullptr));
        label_40->setText(QCoreApplication::translate("Eeprom", "Laser Width [ns]", nullptr));
        label_41->setText(QCoreApplication::translate("Eeprom", "Laser Wavelength [nm]", nullptr));
        label_42->setText(QCoreApplication::translate("Eeprom", "Spectra Stored to RAM", nullptr));
        groupBox_9->setTitle(QCoreApplication::translate("Eeprom", "Dark Correction Settings", nullptr));
        DarkCorrEnableChk->setText(QCoreApplication::translate("Eeprom", "Enable", nullptr));
        label_54->setText(QCoreApplication::translate("Eeprom", "%", nullptr));
        label_6->setText(QCoreApplication::translate("Eeprom", "Start Pixel", nullptr));
        label_27->setText(QCoreApplication::translate("Eeprom", "Stop Pixel", nullptr));
        label_28->setText(QCoreApplication::translate("Eeprom", "Integration Time [ms]", nullptr));
        label_29->setText(QCoreApplication::translate("Eeprom", "Integration Delay [ns]", nullptr));
        label_30->setText(QCoreApplication::translate("Eeprom", "Number of Averages", nullptr));
        label_31->setText(QCoreApplication::translate("Eeprom", "Saturation Detection", nullptr));
        groupBox_11->setTitle(QCoreApplication::translate("Eeprom", "Smoothing Settings", nullptr));
        label_35->setText(QCoreApplication::translate("Eeprom", "Model", nullptr));
        label_36->setText(QCoreApplication::translate("Eeprom", "TextLabel", nullptr));
        label_37->setText(QCoreApplication::translate("Eeprom", "Nr of Pixels", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("Eeprom", "Trigger Settings", nullptr));
        groupBox_18->setTitle(QCoreApplication::translate("Eeprom", "Trigger Mode", nullptr));
        HardwareTriggerRBtn->setText(QCoreApplication::translate("Eeprom", "Hardware", nullptr));
        SoftwareTriggerRBtn->setText(QCoreApplication::translate("Eeprom", "Software", nullptr));
        groupBox_19->setTitle(QCoreApplication::translate("Eeprom", "Trigger Source", nullptr));
        ExternalTriggerRbtn->setText(QCoreApplication::translate("Eeprom", "External", nullptr));
        SynchTriggerRBtn->setText(QCoreApplication::translate("Eeprom", "Synchronized", nullptr));
        groupBox_21->setTitle(QCoreApplication::translate("Eeprom", "Trigger Type", nullptr));
        EdgeTriggerRBtn->setText(QCoreApplication::translate("Eeprom", "Edge", nullptr));
        LevelTriggerRBtn->setText(QCoreApplication::translate("Eeprom", "Level", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("Eeprom", "SDCard Settings", nullptr));
        groupBox_10->setTitle(QCoreApplication::translate("Eeprom", "TimeStamp", nullptr));
        GetTimeStampChk->setText(QCoreApplication::translate("Eeprom", "Get TimeStamp from PC", nullptr));
        label_46->setText(QCoreApplication::translate("Eeprom", "DateNr", nullptr));
        label_47->setText(QCoreApplication::translate("Eeprom", "Day (0-31)", nullptr));
        label_48->setText(QCoreApplication::translate("Eeprom", "Month (1-12)", nullptr));
        label_49->setText(QCoreApplication::translate("Eeprom", "Year -/- 1980", nullptr));
        label_50->setText(QCoreApplication::translate("Eeprom", "TimeNr", nullptr));
        label_51->setText(QCoreApplication::translate("Eeprom", "0.5*Sec (0-30)", nullptr));
        label_52->setText(QCoreApplication::translate("Eeprom", "Minutes (0-59)", nullptr));
        label_53->setText(QCoreApplication::translate("Eeprom", "Hours (0-23)", nullptr));
        SDCardEnableChk->setText(QCoreApplication::translate("Eeprom", "Enable", nullptr));
        label_44->setText(QCoreApplication::translate("Eeprom", "Spectrum Type", nullptr));
        label_45->setText(QCoreApplication::translate("Eeprom", "FileRootName", nullptr));
        label_43->setText(QCoreApplication::translate("Eeprom", "Nr of Measurements", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(StandaloneTab), QCoreApplication::translate("Eeprom", "Standalone", nullptr));
        groupBox_12->setTitle(QCoreApplication::translate("Eeprom", "Scope to Irradiance Conversion", nullptr));
        groupBox_13->setTitle(QCoreApplication::translate("Eeprom", "Calibration Smoothing Settings", nullptr));
        label_55->setText(QCoreApplication::translate("Eeprom", "Model", nullptr));
        label_56->setText(QCoreApplication::translate("Eeprom", "Nr of Pixels", nullptr));
        label_57->setText(QCoreApplication::translate("Eeprom", "Calibration IntegrationTime [ms]", nullptr));
        label_58->setText(QCoreApplication::translate("Eeprom", "Irradiance Calibration Type", nullptr));
        label_59->setText(QCoreApplication::translate("Eeprom", "Irradiance Fiber Diameter [micron]", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(IrradianceTab), QCoreApplication::translate("Eeprom", "Irradiance Calibration", nullptr));
        groupBox_14->setTitle(QCoreApplication::translate("Eeprom", "Scope to Reflectance Conversion", nullptr));
        groupBox_15->setTitle(QCoreApplication::translate("Eeprom", "Calibration Smoothing Settings", nullptr));
        label_60->setText(QCoreApplication::translate("Eeprom", "Model", nullptr));
        label_61->setText(QCoreApplication::translate("Eeprom", "Nr of Pixels", nullptr));
        label_62->setText(QCoreApplication::translate("Eeprom", "Calibration IntegrationTime [ms]", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(ReflectanceTab), QCoreApplication::translate("Eeprom", "Reflectance Calibration", nullptr));
        groupBox_16->setTitle(QCoreApplication::translate("Eeprom", "Pixel Correction Values", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(SpectrumTab), QCoreApplication::translate("Eeprom", "Spectrum Correction", nullptr));
        groupBox_17->setTitle(QCoreApplication::translate("Eeprom", "NTC1 Calibration", nullptr));
        label_63->setText(QCoreApplication::translate("Eeprom", "Intercept", nullptr));
        label_64->setText(QCoreApplication::translate("Eeprom", "X1", nullptr));
        label_65->setText(QCoreApplication::translate("Eeprom", "X2", nullptr));
        label_66->setText(QCoreApplication::translate("Eeprom", "X3", nullptr));
        label_67->setText(QCoreApplication::translate("Eeprom", "X4", nullptr));
        groupBox_20->setTitle(QCoreApplication::translate("Eeprom", "NTC2 Calibration", nullptr));
        label_78->setText(QCoreApplication::translate("Eeprom", "Intercept", nullptr));
        label_79->setText(QCoreApplication::translate("Eeprom", "X1", nullptr));
        label_80->setText(QCoreApplication::translate("Eeprom", "X2", nullptr));
        label_81->setText(QCoreApplication::translate("Eeprom", "X3", nullptr));
        label_82->setText(QCoreApplication::translate("Eeprom", "X4", nullptr));
        groupBox_23->setTitle(QCoreApplication::translate("Eeprom", "Thermistor Calibration", nullptr));
        label_93->setText(QCoreApplication::translate("Eeprom", "Intercept", nullptr));
        label_94->setText(QCoreApplication::translate("Eeprom", "X1", nullptr));
        label_95->setText(QCoreApplication::translate("Eeprom", "X2", nullptr));
        label_96->setText(QCoreApplication::translate("Eeprom", "X3", nullptr));
        label_97->setText(QCoreApplication::translate("Eeprom", "X4", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(TemperatureTab), QCoreApplication::translate("Eeprom", "Temperature Sensors", nullptr));
        groupBox_24->setTitle(QCoreApplication::translate("Eeprom", "DAC Coefficients", nullptr));
        label_99->setText(QCoreApplication::translate("Eeprom", "X0", nullptr));
        label_100->setText(QCoreApplication::translate("Eeprom", "X1", nullptr));
        TECEnableChk->setText(QCoreApplication::translate("Eeprom", "Enable", nullptr));
        label_98->setText(QCoreApplication::translate("Eeprom", "SetPoint [degree C]", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(TecTab), QCoreApplication::translate("Eeprom", "Tec Control", nullptr));
        label->setText(QCoreApplication::translate("Eeprom", "Structure Length [bytes]", nullptr));
        label_2->setText(QCoreApplication::translate("Eeprom", "Structure Version", nullptr));
        label_3->setText(QCoreApplication::translate("Eeprom", "Friendly Name", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Eeprom: public Ui_Eeprom {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EEPROM_H
